networks:
  kdx_external:
    external: true
  kdx_internal:
    external: true



services:
  next-app:
    container_name: next-app
    build:
      context: .
    restart: always
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - 'traefik.http.routers.mcq.rule=Host(`mcq.box.kitty-dev.com`)' # will use the wildcard subdomain certificate
      - "traefik.http.routers.mcq.entrypoints=https"
      - "traefik.http.routers.mcq.tls=true"
      - "traefik.http.services.mcq.loadbalancer.server.port=3000"
    networks:
      - kdx_external
      - kdx_internal

#kubectl create secret docker-registry kxd-register-secret --docker-server=register.infra.kittxdev.com --docker-username=kittxdev --docker-password=Minnow@2025 -n mcq
