import {ApplicationLayout} from "@/app/home/application-layout";
import Providers from "@/app/redux/provider";
import '@/styles/tailwind.css'
export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        <Providers>
            <ApplicationLayout>
                {children}
            </ApplicationLayout>
        </Providers>
        </body>
        </html>
    )
}
